// Biome palette registry. Each entry lists CSS variable overrides
// applied on top of the midnight-loom base theme when the player is in
// that biome. Generated by scripts/gen-biome-themes.mjs.

import palettes from "../../biomes/palettes.json" with { type: "json" };

export type BiomePalette = {
	slug: string;
	name: string;
	mood: string;
	overrides: Record<string, string>;
};

const BY_SLUG = new Map<string, BiomePalette>(
	(palettes.palettes as unknown as BiomePalette[]).map((p) => [p.slug, p]),
);

/** Look up a palette by biome slug. Returns null when no override is known
 *  so the UI falls through to the default midnight-loom theme. */
export function getBiomePalette(slug: string | null | undefined): BiomePalette | null {
	if (!slug) return null;
	return BY_SLUG.get(slug) ?? null;
}

/** Serialize a palette's overrides as a CSS :root rule. Safe for inlining
 *  into a <style> tag — no user-supplied values reach it (palettes are
 *  vetted at generate time). */
export function paletteToCss(palette: BiomePalette): string {
	const lines = Object.entries(palette.overrides)
		.map(([key, value]) => `  ${key}: ${value};`)
		.join("\n");
	return `:root {\n${lines}\n}`;
}

export function listPalettes(): BiomePalette[] {
	return [...BY_SLUG.values()];
}
